services:
  bootlegspotifyapi:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=https://+:5000
    ports:
      - "5000:5000"
      - "5001:5001"
